version: "3.2"
services:
  qbittorrent:
    container_name: qBittorrent
    environment:
      - TZ=Asia/Shanghai
      - TemPath=/downloads
      - SavePath=/downloads
      - PGID=1000
      - PUID=1000
      - WEBUI_PORT=7896
    volumes:
      - qb_config:/config
      - /data/downloads:/downloads # 填入下载绝对路径
    ports:
      - 7896:7896
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - auto_bangumi
    restart: unless-stopped
    image: superng6/qbittorrent

  auto_bangumi:
    container_name: AutoBangumi
    environment:
      - TZ=Asia/Shanghai
      - PGID=1000
      - PUID=1000
      - AB_DOWNLOADER_HOST=qbittorrent:7896
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    networks:
      - auto_bangumi
    ports:
      - '6789:7892'
    dns:
      - 8.8.8.8
      - 223.5.5.5
    restart: unless-stopped
    image: estrellaxd/auto_bangumi:latest
    depends_on:
      - qbittorrent

  alist:
    restart: always
    volumes:
        - '/etc/alist:/opt/alist/data'
    ports:
        - '5244:5244'
    environment:
        - PUID=1000
        - PGID=1000
        - UMASK=022
    container_name: alist
    image: 'xhofe/alist:latest'

networks:
  auto_bangumi:
volumes:
  qb_config:
    external: false
